### ISSUE TITLE
Bug: commands on same line in transform result

### ISSUE THREAD

**Issue by ronanliu** [anevis/datadog-to-terraform-js#21]
Hi Antony,

Hope you are doing good.

We've encounter an issue when use the tool. After transformation, multiple commands are ended on the same line, which is invalid formatting in terraform. At the moment, we have to manually update them.
![image](https://user-images.githubusercontent.com/48817774/116503080-9039e080-a8f8-11eb-9cef-acd461068fb6.png)
Could you please help us to correct the issue? Thanks!

**Comment by anevis** [comment]
We currently don't support formatting
